[package]
name = "manifest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
glam = "0.24.0"
json = "0.12.4"
paste = "1.0.12"
rfd = "0.11.4"
